network:
        version: 2
        renderer: networkd

        ethernets:
                # Spot GXP:
                eth2:
                        dhcp4: no
                        addresses: [192.168.50.100/16]
    
                # Velodyne:
                eth1:
                        dhcp4: no
                        addresses: [192.168.1.100/24]
